# Server
server.port=8080

# Supabase PostgreSQL connection
#spring.datasource.url=jdbc:postgresql://db.gwqgotbobzedkhiuomqx.supabase.co:5432/postgres?user=postgres&password=cL0MBXFWt7EMyHNA
#spring.datasource.url=jdbc:postgresql://db.vbdkpywuhuibapgngvid.supabase.co:5432/postgres?user=postgres&password=wNU4HqZRNhLjiqzW
spring.datasource.url=jdbc:postgresql://db.vbdkpywuhuibapgngvid.supabase.co:5432/postgres

spring.datasource.username=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tell Spring to use H2 instead of Postgres
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect